updated Readme file and buildspec file for the stage required condition

diff --git a/aws-codepipeline/cloudformation/shared/cfn-lint-buildspec.yaml b/aws-codepipeline/cloudformation/shared/cfn-lint-buildspec.yaml
--- a/aws-codepipeline/cloudformation/shared/cfn-lint-buildspec.yaml
+++ b/aws-codepipeline/cloudformation/shared/cfn-lint-buildspec.yaml
@@ -20,54 +20,54 @@ phases:
       - ls -l
       - |
         ENV_TYPE=$( jq -r '.envType' entrypoint/config.json )
-        stage_required=$( jq -r '.stage_required' entrypoint/config.json )
+        init_stage_required=$( jq -r '.init_stage_required' entrypoint/config.json )
         cft_s3_bucket=$( jq -r '.cft_s3_bucket' entrypoint/config.json )
         stack_name=$( jq -r '.stack_name' entrypoint/config.json )
-        if [ $stage_required == "false" ]; then
+        if [ $init_stage_required == "false" ]; then
             echo "skipping the stage"
             exit 0
+        else
+            if [ $ENV_TYPE == "terraform" ]; then 
+                  echo "terraform"
+            elif [ $ENV_TYPE == "cloudformation" ]; then
+                  echo "cloudformation"
+                  cfn-lint -t *.yaml
+                  exitcode=$?
+                  if [ $exitcode = 2 ]; then
+                     echo "template has exit code 2 linting error"
+                     exit
+                  elif [ $exitcode = 6 ]; then
+                     echo "template has exit code 6 linting error and warning"
+                     exit
+                  elif [ $exitcode = 10 ]; then
+                     echo "template has exit code 10 error and informational"
+                     exit
+                  elif [ $exitcode = 14 ]; then
+                     echo "template has exit code 14 error and a warning and informational"
+                     exit
+                  fi
+                  cfn-lint -t nested/*.yaml
+                  exitcode=$?
+                  if [ $exitcode = 2 ]; then
+                     echo "template has exit code 2 linting error"
+                     exit
+                  elif [ $exitcode = 6 ]; then
+                     echo "template has exit code 6 linting error and warning"
+                     exit
+                  elif [ $exitcode = 10 ]; then
+                     echo "template has exit code 10 error and informational"
+                     exit
+                  elif [ $exitcode = 14 ]; then
+                     echo "template has exit code 14 error and a warning and informational"
+                     exit
+                  fi
+            elif [ $ENV_TYPE == "cdk" ]; then
+                  echo "cdk"
+            else 
+               exit 1
+               echo "check the envType variable input in the config.json file"
+            fi 
         fi
-        if [ $ENV_TYPE == "terraform" ]; then 
-            echo "terraform"
-        elif [ $ENV_TYPE == "cloudformation" ]; then
-            echo "cloudformation"
-            cfn-lint -t *.yaml
-            exitcode=$?
-            if [ $exitcode = 2 ]; then
-               echo "template has exit code 2 linting error"
-               exit
-            elif [ $exitcode = 6 ]; then
-               echo "template has exit code 6 linting error and warning"
-               exit
-            elif [ $exitcode = 10 ]; then
-               echo "template has exit code 10 error and informational"
-               exit
-            elif [ $exitcode = 14 ]; then
-               echo "template has exit code 14 error and a warning and informational"
-               exit
-            fi
-            cfn-lint -t nested/*.yaml
-            exitcode=$?
-            if [ $exitcode = 2 ]; then
-               echo "template has exit code 2 linting error"
-               exit
-            elif [ $exitcode = 6 ]; then
-               echo "template has exit code 6 linting error and warning"
-               exit
-            elif [ $exitcode = 10 ]; then
-               echo "template has exit code 10 error and informational"
-               exit
-            elif [ $exitcode = 14 ]; then
-               echo "template has exit code 14 error and a warning and informational"
-               exit
-            fi
-        elif [ $ENV_TYPE == "cdk" ]; then
-            echo "cdk"
-        else 
-           exit 1
-           echo "check the envType variable input in the config.json file"
-        fi 
-        
   post_build:
     commands:
       - echo "Display Last Changes"
diff --git a/aws-codepipeline/cloudformation/shared/cfn-nag-buildspec.yaml b/aws-codepipeline/cloudformation/shared/cfn-nag-buildspec.yaml
--- a/aws-codepipeline/cloudformation/shared/cfn-nag-buildspec.yaml
+++ b/aws-codepipeline/cloudformation/shared/cfn-nag-buildspec.yaml
@@ -20,33 +20,35 @@ phases:
       - ls -l
       - |
         ENV_TYPE=$( jq -r '.envType' entrypoint/config.json )
-        stage_required=$( jq -r '.stage_required' entrypoint/config.json )
+        test_stage_required=$( jq -r '.test_stage_required' entrypoint/config.json )
         cft_s3_bucket=$( jq -r '.cft_s3_bucket' entrypoint/config.json )
         stack_name=$( jq -r '.stack_name' entrypoint/config.json )
-        if [ $stage_required == "false" ]; then
+        current_time=$(date "+%Y.%m.%d-%H.%M.%S")
+        if [ $test_stage_required == "false" ]; then
             echo "skipping the stage"
             exit 0
+        else
+            if [ $ENV_TYPE == "terraform" ]; then 
+                echo "terraform"
+            elif [ $ENV_TYPE == "cloudformation" ]; then
+                echo "cloudformation"
+                cfn_nag nested/* -t json > cfnoutput_$current_time.json
+                for i in $(jq -r '.[] | .file_results.failure_count' cfnoutput_$current_time.json); do 
+                  aws s3 cp cfnoutput_$current_time.json s3://$cft_s3_bucket/cfn_nag_output/
+                  if [ $i -gt 0 ]; 
+                  then
+                    echo "Template has CFN_NAG failures"
+                    exit 1
+                  else
+                    echo "Template has no failures"
+                done
+            elif [ $ENV_TYPE == "cdk" ]; then
+                echo "cdk"
+            else 
+              exit 1
+              echo "check the envType variable input in the config.json file"
+            fi 
         fi
-        if [ $ENV_TYPE == "terraform" ]; then 
-            echo "terraform"
-        elif [ $ENV_TYPE == "cloudformation" ]; then
-            echo "cloudformation"
-            cfn_nag nested/* -t json > cfnoutput.json
-            for i in $(jq -r '.[] | .file_results.failure_count' cfnoutput.json); do 
-              if [ $i -gt 0 ]; 
-              then
-                echo "Template has CFN_NAG failures"
-                exit 1
-              else
-                echo "Template has no failures"
-            done
-        elif [ $ENV_TYPE == "cdk" ]; then
-            echo "cdk"
-        else 
-           exit 1
-           echo "check the envType variable input in the config.json file"
-        fi 
-        
   post_build:
     commands:
       - echo "Display Last Changes"
